### ISSUE TITLE
BH Contracts To-Do List:

### ISSUE THREAD

**Issue by DeltaDizzy** [Gameslinx/BeyondHomePlanetMod#2]
### General
- [ ] First Flight/First Science (one contract)
- [ ] Escape the Atmosphere

### Uncrewed
- [ ] Orbit Rhode
#### For each Celestial Body
- [ ] Flyby
- [ ] Impact
- [ ] Orbit
- [ ] Land

### Crewed
- [ ] Orbit Rhode
#### For each Celestial Body
- [ ] Orbit OR FlyBy
- [ ] Land
- [ ] Base?
- [ ] Station?
